version: '3.7'
services:
   client:
      build:
         context: ./los_frontend
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./los_frontend:/app1
         - /app1/node_modules
      networks:
            - los_frontend


   mongodb:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        volumes:
            - mongodbdata:/data/db
        ports:
            - "27017:27017"
        networks:
            - los_backend


   api:
        build: 
            context: ./los_backend
            dockerfile: Dockerfile
        command: >
           sh -c "python manage.py makemigrations &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - appdata:/var/www/
        depends_on: 
            - mongodb
        networks:
            - los_frontend
            - los_backend


networks:
    los_frontend:
        driver: bridge
    los_backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local

